### ISSUE TITLE
Bookmarks toolbar is not styled

### ISSUE THREAD

**Issue by bermudalocket** [diedummydie/Safari-Theme-for-Firefox#1]
See screenshot:

<img width="275" alt="Screen Shot 2019-10-19 at 2 03 50 PM" src="https://user-images.githubusercontent.com/30004636/67149440-4c810800-f279-11e9-9d64-d408644221ce.png">

**Comment by diedummydie** [comment]
Thanks for pointing this out. Fixed via #5be84c79f39c476c280a87360470ecb081bd36f7.

![Screen Shot 2019-10-23 at 3 30 15 PM](https://user-images.githubusercontent.com/1759544/67428424-9ea19080-f5cd-11e9-843c-7be1f4d41447.png)

This adds the same background gradient, hover gradient, hover text color inversion, slightly larger padding, and top border, in a way that works with both light mode and dark mode. If I were doing this solely according to my own taste, I would remove the top border and the extra top padding, but it's probably better to mirror Safari as closely as possible.
