### ISSUE TITLE
Active extension button applies background to icon

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#12]
When an extension button is active, the background is applied to the toolbarbutton-icon, where it should only be applied to the stack.

![Active extension button](https://user-images.githubusercontent.com/52195359/68080572-acb7a280-fe52-11e9-871b-189a750eb11e.png)

**Comment by diedummydie** [comment]
Most built in buttons don't have a stack, but restricting the icon selector with ~~`:not(.webextension-browser-action)`~~ `:not([badged="true"])` stops the effect from being double applied.
