### ISSUE TITLE
Extension icons too wide in buttons

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#14]
A good example of this is in [my comment on another issue](https://github.com/diedummydie/Safari-Theme-for-Firefox/issues/9#issuecomment-549104337).

**Comment by diedummydie** [comment]
Another HiDPI regression. Icon size is constrained by stack padding, and changing that to 3.25x11 brings the icons back to a 16x16 square (and 32x32 @2x).
