### ISSUE TITLE
Hiding Tabs panel when you have only 1 tab?

### ISSUE THREAD

**Issue by ghost** [diedummydie/Safari-Theme-for-Firefox#15]
Hi,

I am having an issue (or maybe is not a feature) with the theme. Safari's behaviour when you only have one tab open is to completely hide the panel. Even though I see a CSS file that suggest this is possible with this theme It is not working for me on FF 70.

![imagen](https://user-images.githubusercontent.com/31588962/68379485-3666b900-014e-11ea-8609-5b04c34f1147.png)

I've seen other themes accomplish this with this extension https://addons.mozilla.org/en-US/firefox/addon/tab-count-in-window-title/

Thank you!

**Comment by diedummydie** [comment]
Okay, I'll take a look at that.
