### ISSUE TITLE
Pages with no favicon cause the title to move

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#3]
![No Favicon](https://user-images.githubusercontent.com/52195359/67927819-aa183b80-fc0d-11e9-81c5-a3e0206e0e38.gif)

The page title is centered, so when the close button appears the title is moved. The title should either be centered with an offset or the favicon should not affect the title.

Which is the better option in this situation? Personally I think the title should be centered as if the favicon/close button wasn't there at all, but it's your call. Happy to create a PR if you want!

**Comment by clo4** [comment]
Actually after giving it some thought, it would probably be best for text in tabs *without a favicon* to have a left margin, to avoid the text possibly overlapping the image.

If the text for all tabs was properly centered that could cause some unfortunate visual problems that might be more effort than they're worth to fix.

**Comment by diedummydie** [comment]
Sites with no favicon now have one.
