### ISSUE TITLE
Enforced code style?

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#6]
Using a standard code formatter such as [Prettier](https://prettier.io/) would ensure a consistent code style and make it easier for people to jump in and read, as well as relieve some of the mental load of manually formatting the CSS.

IMO it would be a good idea to use one for this project. Thoughts?

**Comment by diedummydie** [comment]
This is a good idea. 

I'm using the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) with `formatOnSave` enabled. No config changes. 

> Nobody loves what Prettier does to their syntax
> Everyone loves what Prettier does to their coworkers' syntax
