### ISSUE TITLE
No visual feedback on button click

### ISSUE THREAD

**Issue by clo4** [diedummydie/Safari-Theme-for-Firefox#7]
Safari uses a different background color when navbar buttons are active to show the user that they are clicking an interactive piece of the UI. This theme should provide a similar visual feedback for input.

Safari uses a darker color for its light theme and a lighter color for its dark theme. The two example images below have the back button active.

![Safari Light](https://user-images.githubusercontent.com/52195359/67959352-b7084f80-fc4c-11e9-923a-e3a719f61b02.png)

![Safari Dark](https://user-images.githubusercontent.com/52195359/67959485-ed45cf00-fc4c-11e9-9ddf-1b9ac26d4667.png)

**Comment by diedummydie** [comment]
Buttons in the UI now slightly darken when pressed in the light theme, and slightly brighten when pressed in the dark theme.
